import { Factory } from '@mikro-orm/seeder';
import { Country } from './country.entity';

export class CountryFactory extends Factory<Country> {
  model = Country;

  definition(): Partial<Country> {
    return {};
  }

  createAll(): Country[] {
    return [
      this.makeOne({ id: 1, code: 'AF', name: 'Afghanistan', phoneCode: 93 }),
      this.makeOne({ id: 2, code: 'AL', name: 'Albania', phoneCode: 355 }),
      this.makeOne({ id: 3, code: 'DZ', name: 'Algeria', phoneCode: 213 }),
      this.makeOne({
        id: 4,
        code: 'AS',
        name: 'American Samoa',
        phoneCode: 1684,
      }),
      this.makeOne({ id: 5, code: 'AD', name: 'Andorra', phoneCode: 376 }),
      this.makeOne({ id: 6, code: 'AO', name: 'Angola', phoneCode: 244 }),
      this.makeOne({ id: 7, code: 'AI', name: 'Anguilla', phoneCode: 1264 }),
      this.makeOne({ id: 8, code: 'AQ', name: 'Antarctica', phoneCode: 0 }),
      this.makeOne({
        id: 9,
        code: 'AG',
        name: 'Antigua And Barbuda',
        phoneCode: 1268,
      }),
      this.makeOne({ id: 10, code: 'AR', name: 'Argentina', phoneCode: 54 }),
      this.makeOne({ id: 11, code: 'AM', name: 'Armenia', phoneCode: 374 }),
      this.makeOne({ id: 12, code: 'AW', name: 'Aruba', phoneCode: 297 }),
      this.makeOne({ id: 13, code: 'AU', name: 'Australia', phoneCode: 61 }),
      this.makeOne({ id: 14, code: 'AT', name: 'Austria', phoneCode: 43 }),
      this.makeOne({ id: 15, code: 'AZ', name: 'Azerbaijan', phoneCode: 994 }),
      this.makeOne({
        id: 16,
        code: 'BS',
        name: 'Bahamas The',
        phoneCode: 1242,
      }),
      this.makeOne({ id: 17, code: 'BH', name: 'Bahrain', phoneCode: 973 }),
      this.makeOne({ id: 18, code: 'BD', name: 'Bangladesh', phoneCode: 880 }),
      this.makeOne({ id: 19, code: 'BB', name: 'Barbados', phoneCode: 1246 }),
      this.makeOne({ id: 20, code: 'BY', name: 'Belarus', phoneCode: 375 }),
      this.makeOne({ id: 21, code: 'BE', name: 'Belgium', phoneCode: 32 }),
      this.makeOne({ id: 22, code: 'BZ', name: 'Belize', phoneCode: 501 }),
      this.makeOne({ id: 23, code: 'BJ', name: 'Benin', phoneCode: 229 }),
      this.makeOne({ id: 24, code: 'BM', name: 'Bermuda', phoneCode: 1441 }),
      this.makeOne({ id: 25, code: 'BT', name: 'Bhutan', phoneCode: 975 }),
      this.makeOne({ id: 26, code: 'BO', name: 'Bolivia', phoneCode: 591 }),
      this.makeOne({
        id: 27,
        code: 'BA',
        name: 'Bosnia and Herzegovina',
        phoneCode: 387,
      }),
      this.makeOne({ id: 28, code: 'BW', name: 'Botswana', phoneCode: 267 }),
      this.makeOne({ id: 29, code: 'BV', name: 'Bouvet Island', phoneCode: 0 }),
      this.makeOne({ id: 30, code: 'BR', name: 'Brazil', phoneCode: 55 }),
      this.makeOne({
        id: 31,
        code: 'IO',
        name: 'British Indian Ocean Territory',
        phoneCode: 246,
      }),
      this.makeOne({ id: 32, code: 'BN', name: 'Brunei', phoneCode: 673 }),
      this.makeOne({ id: 33, code: 'BG', name: 'Bulgaria', phoneCode: 359 }),
      this.makeOne({
        id: 34,
        code: 'BF',
        name: 'Burkina Faso',
        phoneCode: 226,
      }),
      this.makeOne({ id: 35, code: 'BI', name: 'Burundi', phoneCode: 257 }),
      this.makeOne({ id: 36, code: 'KH', name: 'Cambodia', phoneCode: 855 }),
      this.makeOne({ id: 37, code: 'CM', name: 'Cameroon', phoneCode: 237 }),
      this.makeOne({ id: 38, code: 'CA', name: 'Canada', phoneCode: 1 }),
      this.makeOne({ id: 39, code: 'CV', name: 'Cape Verde', phoneCode: 238 }),
      this.makeOne({
        id: 40,
        code: 'KY',
        name: 'Cayman Islands',
        phoneCode: 1345,
      }),
      this.makeOne({
        id: 41,
        code: 'CF',
        name: 'Central African Republic',
        phoneCode: 236,
      }),
      this.makeOne({ id: 42, code: 'TD', name: 'Chad', phoneCode: 235 }),
      this.makeOne({ id: 43, code: 'CL', name: 'Chile', phoneCode: 56 }),
      this.makeOne({ id: 44, code: 'CN', name: 'China', phoneCode: 86 }),
      this.makeOne({
        id: 45,
        code: 'CX',
        name: 'Christmas Island',
        phoneCode: 61,
      }),
      this.makeOne({
        id: 46,
        code: 'CC',
        name: 'Cocos (Keeling) Islands',
        phoneCode: 672,
      }),
      this.makeOne({ id: 47, code: 'CO', name: 'Colombia', phoneCode: 57 }),
      this.makeOne({ id: 48, code: 'KM', name: 'Comoros', phoneCode: 269 }),
      this.makeOne({ id: 49, code: 'CG', name: 'Congo', phoneCode: 242 }),
      this.makeOne({
        id: 50,
        code: 'CD',
        name: 'Congo The Democratic Republic Of The',
        phoneCode: 242,
      }),
      this.makeOne({
        id: 51,
        code: 'CK',
        name: 'Cook Islands',
        phoneCode: 682,
      }),
      this.makeOne({ id: 52, code: 'CR', name: 'Costa Rica', phoneCode: 506 }),
      this.makeOne({
        id: 53,
        code: 'CI',
        name: 'Cote D Ivoire (Ivory Coast)',
        phoneCode: 225,
      }),
      this.makeOne({
        id: 54,
        code: 'HR',
        name: 'Croatia (Hrvatska)',
        phoneCode: 385,
      }),
      this.makeOne({ id: 55, code: 'CU', name: 'Cuba', phoneCode: 53 }),
      this.makeOne({ id: 56, code: 'CY', name: 'Cyprus', phoneCode: 357 }),
      this.makeOne({
        id: 57,
        code: 'CZ',
        name: 'Czech Republic',
        phoneCode: 420,
      }),
      this.makeOne({ id: 58, code: 'DK', name: 'Denmark', phoneCode: 45 }),
      this.makeOne({ id: 59, code: 'DJ', name: 'Djibouti', phoneCode: 253 }),
      this.makeOne({ id: 60, code: 'DM', name: 'Dominica', phoneCode: 1767 }),
      this.makeOne({
        id: 61,
        code: 'DO',
        name: 'Dominican Republic',
        phoneCode: 1809,
      }),
      this.makeOne({ id: 62, code: 'TP', name: 'East Timor', phoneCode: 670 }),
      this.makeOne({ id: 63, code: 'EC', name: 'Ecuador', phoneCode: 593 }),
      this.makeOne({ id: 64, code: 'EG', name: 'Egypt', phoneCode: 20 }),
      this.makeOne({ id: 65, code: 'SV', name: 'El Salvador', phoneCode: 503 }),
      this.makeOne({
        id: 66,
        code: 'GQ',
        name: 'Equatorial Guinea',
        phoneCode: 240,
      }),
      this.makeOne({ id: 67, code: 'ER', name: 'Eritrea', phoneCode: 291 }),
      this.makeOne({ id: 68, code: 'EE', name: 'Estonia', phoneCode: 372 }),
      this.makeOne({ id: 69, code: 'ET', name: 'Ethiopia', phoneCode: 251 }),
      this.makeOne({
        id: 70,
        code: 'XA',
        name: 'External Territories of Australia',
        phoneCode: 61,
      }),
      this.makeOne({
        id: 71,
        code: 'FK',
        name: 'Falkland Islands',
        phoneCode: 500,
      }),
      this.makeOne({
        id: 72,
        code: 'FO',
        name: 'Faroe Islands',
        phoneCode: 298,
      }),
      this.makeOne({
        id: 73,
        code: 'FJ',
        name: 'Fiji Islands',
        phoneCode: 679,
      }),
      this.makeOne({ id: 74, code: 'FI', name: 'Finland', phoneCode: 358 }),
      this.makeOne({ id: 75, code: 'FR', name: 'France', phoneCode: 33 }),
      this.makeOne({
        id: 76,
        code: 'GF',
        name: 'French Guiana',
        phoneCode: 594,
      }),
      this.makeOne({
        id: 77,
        code: 'PF',
        name: 'French Polynesia',
        phoneCode: 689,
      }),
      this.makeOne({
        id: 78,
        code: 'TF',
        name: 'French Southern Territories',
        phoneCode: 0,
      }),
      this.makeOne({ id: 79, code: 'GA', name: 'Gabon', phoneCode: 241 }),
      this.makeOne({ id: 80, code: 'GM', name: 'Gambia The', phoneCode: 220 }),
      this.makeOne({ id: 81, code: 'GE', name: 'Georgia', phoneCode: 995 }),
      this.makeOne({ id: 82, code: 'DE', name: 'Germany', phoneCode: 49 }),
      this.makeOne({ id: 83, code: 'GH', name: 'Ghana', phoneCode: 233 }),
      this.makeOne({ id: 84, code: 'GI', name: 'Gibraltar', phoneCode: 350 }),
      this.makeOne({ id: 85, code: 'GR', name: 'Greece', phoneCode: 30 }),
      this.makeOne({ id: 86, code: 'GL', name: 'Greenland', phoneCode: 299 }),
      this.makeOne({ id: 87, code: 'GD', name: 'Grenada', phoneCode: 1473 }),
      this.makeOne({ id: 88, code: 'GP', name: 'Guadeloupe', phoneCode: 590 }),
      this.makeOne({ id: 89, code: 'GU', name: 'Guam', phoneCode: 1671 }),
      this.makeOne({ id: 90, code: 'GT', name: 'Guatemala', phoneCode: 502 }),
      this.makeOne({
        id: 91,
        code: 'XU',
        name: 'Guernsey and Alderney',
        phoneCode: 44,
      }),
      this.makeOne({ id: 92, code: 'GN', name: 'Guinea', phoneCode: 224 }),
      this.makeOne({
        id: 93,
        code: 'GW',
        name: 'Guinea-Bissau',
        phoneCode: 245,
      }),
      this.makeOne({ id: 94, code: 'GY', name: 'Guyana', phoneCode: 592 }),
      this.makeOne({ id: 95, code: 'HT', name: 'Haiti', phoneCode: 509 }),
      this.makeOne({
        id: 96,
        code: 'HM',
        name: 'Heard and McDonald Islands',
        phoneCode: 0,
      }),
      this.makeOne({ id: 97, code: 'HN', name: 'Honduras', phoneCode: 504 }),
      this.makeOne({
        id: 98,
        code: 'HK',
        name: 'Hong Kong S.A.R.',
        phoneCode: 852,
      }),
      this.makeOne({ id: 99, code: 'HU', name: 'Hungary', phoneCode: 36 }),
      this.makeOne({ id: 100, code: 'IS', name: 'Iceland', phoneCode: 354 }),
      this.makeOne({ id: 101, code: 'IN', name: 'India', phoneCode: 91 }),
      this.makeOne({ id: 102, code: 'ID', name: 'Indonesia', phoneCode: 62 }),
      this.makeOne({ id: 103, code: 'IR', name: 'Iran', phoneCode: 98 }),
      this.makeOne({ id: 104, code: 'IQ', name: 'Iraq', phoneCode: 964 }),
      this.makeOne({ id: 105, code: 'IE', name: 'Ireland', phoneCode: 353 }),
      this.makeOne({ id: 106, code: 'IL', name: 'Israel', phoneCode: 972 }),
      this.makeOne({ id: 107, code: 'IT', name: 'Italy', phoneCode: 39 }),
      this.makeOne({ id: 108, code: 'JM', name: 'Jamaica', phoneCode: 1876 }),
      this.makeOne({ id: 109, code: 'JP', name: 'Japan', phoneCode: 81 }),
      this.makeOne({ id: 110, code: 'XJ', name: 'Jersey', phoneCode: 44 }),
      this.makeOne({ id: 111, code: 'JO', name: 'Jordan', phoneCode: 962 }),
      this.makeOne({ id: 112, code: 'KZ', name: 'Kazakhstan', phoneCode: 7 }),
      this.makeOne({ id: 113, code: 'KE', name: 'Kenya', phoneCode: 254 }),
      this.makeOne({ id: 114, code: 'KI', name: 'Kiribati', phoneCode: 686 }),
      this.makeOne({
        id: 115,
        code: 'KP',
        name: 'Korea North',
        phoneCode: 850,
      }),
      this.makeOne({ id: 116, code: 'KR', name: 'Korea South', phoneCode: 82 }),
      this.makeOne({ id: 117, code: 'KW', name: 'Kuwait', phoneCode: 965 }),
      this.makeOne({ id: 118, code: 'KG', name: 'Kyrgyzstan', phoneCode: 996 }),
      this.makeOne({ id: 119, code: 'LA', name: 'Laos', phoneCode: 856 }),
      this.makeOne({ id: 120, code: 'LV', name: 'Latvia', phoneCode: 371 }),
      this.makeOne({ id: 121, code: 'LB', name: 'Lebanon', phoneCode: 961 }),
      this.makeOne({ id: 122, code: 'LS', name: 'Lesotho', phoneCode: 266 }),
      this.makeOne({ id: 123, code: 'LR', name: 'Liberia', phoneCode: 231 }),
      this.makeOne({ id: 124, code: 'LY', name: 'Libya', phoneCode: 218 }),
      this.makeOne({
        id: 125,
        code: 'LI',
        name: 'Liechtenstein',
        phoneCode: 423,
      }),
      this.makeOne({ id: 126, code: 'LT', name: 'Lithuania', phoneCode: 370 }),
      this.makeOne({ id: 127, code: 'LU', name: 'Luxembourg', phoneCode: 352 }),
      this.makeOne({
        id: 128,
        code: 'MO',
        name: 'Macau S.A.R.',
        phoneCode: 853,
      }),
      this.makeOne({ id: 129, code: 'MK', name: 'Macedonia', phoneCode: 389 }),
      this.makeOne({ id: 130, code: 'MG', name: 'Madagascar', phoneCode: 261 }),
      this.makeOne({ id: 131, code: 'MW', name: 'Malawi', phoneCode: 265 }),
      this.makeOne({ id: 132, code: 'MY', name: 'Malaysia', phoneCode: 60 }),
      this.makeOne({ id: 133, code: 'MV', name: 'Maldives', phoneCode: 960 }),
      this.makeOne({ id: 134, code: 'ML', name: 'Mali', phoneCode: 223 }),
      this.makeOne({ id: 135, code: 'MT', name: 'Malta', phoneCode: 356 }),
      this.makeOne({
        id: 136,
        code: 'XM',
        name: 'Man (Isle of)',
        phoneCode: 44,
      }),
      this.makeOne({
        id: 137,
        code: 'MH',
        name: 'Marshall Islands',
        phoneCode: 692,
      }),
      this.makeOne({ id: 138, code: 'MQ', name: 'Martinique', phoneCode: 596 }),
      this.makeOne({ id: 139, code: 'MR', name: 'Mauritania', phoneCode: 222 }),
      this.makeOne({ id: 140, code: 'MU', name: 'Mauritius', phoneCode: 230 }),
      this.makeOne({ id: 141, code: 'YT', name: 'Mayotte', phoneCode: 269 }),
      this.makeOne({ id: 142, code: 'MX', name: 'Mexico', phoneCode: 52 }),
      this.makeOne({ id: 143, code: 'FM', name: 'Micronesia', phoneCode: 691 }),
      this.makeOne({ id: 144, code: 'MD', name: 'Moldova', phoneCode: 373 }),
      this.makeOne({ id: 145, code: 'MC', name: 'Monaco', phoneCode: 377 }),
      this.makeOne({ id: 146, code: 'MN', name: 'Mongolia', phoneCode: 976 }),
      this.makeOne({
        id: 147,
        code: 'MS',
        name: 'Montserrat',
        phoneCode: 1664,
      }),
      this.makeOne({ id: 148, code: 'MA', name: 'Morocco', phoneCode: 212 }),
      this.makeOne({ id: 149, code: 'MZ', name: 'Mozambique', phoneCode: 258 }),
      this.makeOne({ id: 150, code: 'MM', name: 'Myanmar', phoneCode: 95 }),
      this.makeOne({ id: 151, code: 'NA', name: 'Namibia', phoneCode: 264 }),
      this.makeOne({ id: 152, code: 'NR', name: 'Nauru', phoneCode: 674 }),
      this.makeOne({ id: 153, code: 'NP', name: 'Nepal', phoneCode: 977 }),
      this.makeOne({
        id: 154,
        code: 'AN',
        name: 'Netherlands Antilles',
        phoneCode: 599,
      }),
      this.makeOne({
        id: 155,
        code: 'NL',
        name: 'Netherlands The',
        phoneCode: 31,
      }),
      this.makeOne({
        id: 156,
        code: 'NC',
        name: 'New Caledonia',
        phoneCode: 687,
      }),
      this.makeOne({ id: 157, code: 'NZ', name: 'New Zealand', phoneCode: 64 }),
      this.makeOne({ id: 158, code: 'NI', name: 'Nicaragua', phoneCode: 505 }),
      this.makeOne({ id: 159, code: 'NE', name: 'Niger', phoneCode: 227 }),
      this.makeOne({ id: 160, code: 'NG', name: 'Nigeria', phoneCode: 234 }),
      this.makeOne({ id: 161, code: 'NU', name: 'Niue', phoneCode: 683 }),
      this.makeOne({
        id: 162,
        code: 'NF',
        name: 'Norfolk Island',
        phoneCode: 672,
      }),
      this.makeOne({
        id: 163,
        code: 'MP',
        name: 'Northern Mariana Islands',
        phoneCode: 1670,
      }),
      this.makeOne({ id: 164, code: 'NO', name: 'Norway', phoneCode: 47 }),
      this.makeOne({ id: 165, code: 'OM', name: 'Oman', phoneCode: 968 }),
      this.makeOne({ id: 166, code: 'PK', name: 'Pakistan', phoneCode: 92 }),
      this.makeOne({ id: 167, code: 'PW', name: 'Palau', phoneCode: 680 }),
      this.makeOne({
        id: 168,
        code: 'PS',
        name: 'Palestinian Territory Occupied',
        phoneCode: 970,
      }),
      this.makeOne({ id: 169, code: 'PA', name: 'Panama', phoneCode: 507 }),
      this.makeOne({
        id: 170,
        code: 'PG',
        name: 'Papua new Guinea',
        phoneCode: 675,
      }),
      this.makeOne({ id: 171, code: 'PY', name: 'Paraguay', phoneCode: 595 }),
      this.makeOne({ id: 172, code: 'PE', name: 'Peru', phoneCode: 51 }),
      this.makeOne({ id: 173, code: 'PH', name: 'Philippines', phoneCode: 63 }),
      this.makeOne({
        id: 174,
        code: 'PN',
        name: 'Pitcairn Island',
        phoneCode: 0,
      }),
      this.makeOne({ id: 175, code: 'PL', name: 'Poland', phoneCode: 48 }),
      this.makeOne({ id: 176, code: 'PT', name: 'Portugal', phoneCode: 351 }),
      this.makeOne({
        id: 177,
        code: 'PR',
        name: 'Puerto Rico',
        phoneCode: 1787,
      }),
      this.makeOne({ id: 178, code: 'QA', name: 'Qatar', phoneCode: 974 }),
      this.makeOne({ id: 179, code: 'RE', name: 'Reunion', phoneCode: 262 }),
      this.makeOne({ id: 180, code: 'RO', name: 'Romania', phoneCode: 40 }),
      this.makeOne({ id: 181, code: 'RU', name: 'Russia', phoneCode: 70 }),
      this.makeOne({ id: 182, code: 'RW', name: 'Rwanda', phoneCode: 250 }),
      this.makeOne({
        id: 183,
        code: 'SH',
        name: 'Saint Helena',
        phoneCode: 290,
      }),
      this.makeOne({
        id: 184,
        code: 'KN',
        name: 'Saint Kitts And Nevis',
        phoneCode: 1869,
      }),
      this.makeOne({
        id: 185,
        code: 'LC',
        name: 'Saint Lucia',
        phoneCode: 1758,
      }),
      this.makeOne({
        id: 186,
        code: 'PM',
        name: 'Saint Pierre and Miquelon',
        phoneCode: 508,
      }),
      this.makeOne({
        id: 187,
        code: 'VC',
        name: 'Saint Vincent And The Grenadines',
        phoneCode: 1784,
      }),
      this.makeOne({ id: 188, code: 'WS', name: 'Samoa', phoneCode: 684 }),
      this.makeOne({ id: 189, code: 'SM', name: 'San Marino', phoneCode: 378 }),
      this.makeOne({
        id: 190,
        code: 'ST',
        name: 'Sao Tome and Principe',
        phoneCode: 239,
      }),
      this.makeOne({
        id: 191,
        code: 'SA',
        name: 'Saudi Arabia',
        phoneCode: 966,
      }),
      this.makeOne({ id: 192, code: 'SN', name: 'Senegal', phoneCode: 221 }),
      this.makeOne({ id: 193, code: 'RS', name: 'Serbia', phoneCode: 381 }),
      this.makeOne({ id: 194, code: 'SC', name: 'Seychelles', phoneCode: 248 }),
      this.makeOne({
        id: 195,
        code: 'SL',
        name: 'Sierra Leone',
        phoneCode: 232,
      }),
      this.makeOne({ id: 196, code: 'SG', name: 'Singapore', phoneCode: 65 }),
      this.makeOne({ id: 197, code: 'SK', name: 'Slovakia', phoneCode: 421 }),
      this.makeOne({ id: 198, code: 'SI', name: 'Slovenia', phoneCode: 386 }),
      this.makeOne({
        id: 199,
        code: 'XG',
        name: 'Smaller Territories of the UK',
        phoneCode: 44,
      }),
      this.makeOne({
        id: 200,
        code: 'SB',
        name: 'Solomon Islands',
        phoneCode: 677,
      }),
      this.makeOne({ id: 201, code: 'SO', name: 'Somalia', phoneCode: 252 }),
      this.makeOne({
        id: 202,
        code: 'ZA',
        name: 'South Africa',
        phoneCode: 27,
      }),
      this.makeOne({
        id: 203,
        code: 'GS',
        name: 'South Georgia',
        phoneCode: 0,
      }),
      this.makeOne({
        id: 204,
        code: 'SS',
        name: 'South Sudan',
        phoneCode: 211,
      }),
      this.makeOne({ id: 205, code: 'ES', name: 'Spain', phoneCode: 34 }),
      this.makeOne({ id: 206, code: 'LK', name: 'Sri Lanka', phoneCode: 94 }),
      this.makeOne({ id: 207, code: 'SD', name: 'Sudan', phoneCode: 249 }),
      this.makeOne({ id: 208, code: 'SR', name: 'Suriname', phoneCode: 597 }),
      this.makeOne({
        id: 209,
        code: 'SJ',
        name: 'Svalbard And Jan Mayen Islands',
        phoneCode: 47,
      }),
      this.makeOne({ id: 210, code: 'SZ', name: 'Swaziland', phoneCode: 268 }),
      this.makeOne({ id: 211, code: 'SE', name: 'Sweden', phoneCode: 46 }),
      this.makeOne({ id: 212, code: 'CH', name: 'Switzerland', phoneCode: 41 }),
      this.makeOne({ id: 213, code: 'SY', name: 'Syria', phoneCode: 963 }),
      this.makeOne({ id: 214, code: 'TW', name: 'Taiwan', phoneCode: 886 }),
      this.makeOne({ id: 215, code: 'TJ', name: 'Tajikistan', phoneCode: 992 }),
      this.makeOne({ id: 216, code: 'TZ', name: 'Tanzania', phoneCode: 255 }),
      this.makeOne({ id: 217, code: 'TH', name: 'Thailand', phoneCode: 66 }),
      this.makeOne({ id: 218, code: 'TG', name: 'Togo', phoneCode: 228 }),
      this.makeOne({ id: 219, code: 'TK', name: 'Tokelau', phoneCode: 690 }),
      this.makeOne({ id: 220, code: 'TO', name: 'Tonga', phoneCode: 676 }),
      this.makeOne({
        id: 221,
        code: 'TT',
        name: 'Trinidad And Tobago',
        phoneCode: 1868,
      }),
      this.makeOne({ id: 222, code: 'TN', name: 'Tunisia', phoneCode: 216 }),
      this.makeOne({ id: 223, code: 'TR', name: 'Turkey', phoneCode: 90 }),
      this.makeOne({
        id: 224,
        code: 'TM',
        name: 'Turkmenistan',
        phoneCode: 7370,
      }),
      this.makeOne({
        id: 225,
        code: 'TC',
        name: 'Turks And Caicos Islands',
        phoneCode: 1649,
      }),
      this.makeOne({ id: 226, code: 'TV', name: 'Tuvalu', phoneCode: 688 }),
      this.makeOne({ id: 227, code: 'UG', name: 'Uganda', phoneCode: 256 }),
      this.makeOne({ id: 228, code: 'UA', name: 'Ukraine', phoneCode: 380 }),
      this.makeOne({
        id: 229,
        code: 'AE',
        name: 'United Arab Emirates',
        phoneCode: 971,
      }),
      this.makeOne({
        id: 230,
        code: 'GB',
        name: 'United Kingdom',
        phoneCode: 44,
      }),
      this.makeOne({
        id: 231,
        code: 'US',
        name: 'United States',
        phoneCode: 1,
      }),
      this.makeOne({
        id: 232,
        code: 'UM',
        name: 'United States Minor Outlying Islands',
        phoneCode: 1,
      }),
      this.makeOne({ id: 233, code: 'UY', name: 'Uruguay', phoneCode: 598 }),
      this.makeOne({ id: 234, code: 'UZ', name: 'Uzbekistan', phoneCode: 998 }),
      this.makeOne({ id: 235, code: 'VU', name: 'Vanuatu', phoneCode: 678 }),
      this.makeOne({
        id: 236,
        code: 'VA',
        name: 'Vatican City State (Holy See)',
        phoneCode: 39,
      }),
      this.makeOne({ id: 237, code: 'VE', name: 'Venezuela', phoneCode: 58 }),
      this.makeOne({ id: 238, code: 'VN', name: 'Vietnam', phoneCode: 84 }),
      this.makeOne({
        id: 239,
        code: 'VG',
        name: 'Virgin Islands (British)',
        phoneCode: 1284,
      }),
      this.makeOne({
        id: 240,
        code: 'VI',
        name: 'Virgin Islands (US)',
        phoneCode: 1340,
      }),
      this.makeOne({
        id: 241,
        code: 'WF',
        name: 'Wallis And Futuna Islands',
        phoneCode: 681,
      }),
      this.makeOne({
        id: 242,
        code: 'EH',
        name: 'Western Sahara',
        phoneCode: 212,
      }),
      this.makeOne({ id: 243, code: 'YE', name: 'Yemen', phoneCode: 967 }),
      this.makeOne({ id: 244, code: 'YU', name: 'Yugoslavia', phoneCode: 38 }),
      this.makeOne({ id: 245, code: 'ZM', name: 'Zambia', phoneCode: 260 }),
      this.makeOne({ id: 246, code: 'ZW', name: 'Zimbabwe', phoneCode: 263 }),
    ];
  }
}
